name: Android Build

# Воркфлоу запускается при пуше или создании пул-реквеста в ветку main
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем исходный код репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Устанавливаем Java (JDK 17 — стандарт для современных версий Gradle/Android)
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    # 3. Даем права на выполнение скрипту Gradle (необходимо для Linux окружения)
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 4. Запускаем сборку дебаг-версии APK
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    # 5. Сохраняем готовый APK как артефакт сборки GitHub
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/build/outputs/"
